version: '2'

services:
    quasar:
        image: node:8
        volumes:
            - .:/app
        working_dir: /app
        command: "./node_modules/.bin/nodemon src/server.js"
    npm:
        image: node:8
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: npm
    gulp:
        image: node:8
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: ./node_modules/.bin/gulp
    bower:
        image: node:8
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: "./node_modules/.bin/bower --allow-root"

networks:
    default:
        external:
            name: "container-private"
