version: '2'

services:
    quasar:
        image: node:latest
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: ./node_modules/.bin/nodemon
        command: [-w, "src", src/server.js]
        ports:
            - "8080:8080"
        networks:
            - webproxy

networks:
    webproxy:
        external: true
